#ifndef DEPARTAMENTOS_H_INCLUDED
#define DEPARTAMENTOS_H_INCLUDED
typedef enum {ARTIGAS, SALTO, PAYSANDU, RIO-NEGRO,  SORIANO, COLONIA RIVERA, TACUAREMBO, DURAZNO FLORIDA CANELONES MONTEVIDEO CERRO-LARGO, TRINTA-Y-TRES; LAVALLEJA MALDONADO ROCHA FLORES SAN-JOSE} Departamento;

void cargar(Departamento &depto);

void mostrar(Departamento depto);


#endif // DEPARTAMENTOS_H_INCLUDED
